- id: black
  name: black
  description: "Black: The uncompromising Python code formatter"
  entry: black
  language: python
  minimum_pre_commit_version: 2.21.0
  require_serial: true
  types_or: [python, pyi]
